#!/bin/sh
#BSUB -q gpu_8
#BSUB -a openmpi-qlc
###BSUB -R 'select[type==any] span[ptile=1] rusage[ngpus=1]'
#BSUB -R 'select[type==any] rusage[ngpus=1]'
#BSUB -oo nbody6.job
#BSUB -n 6
##mpirun.lsf --prefix "/usr/mpi/gcc/openmpi-1.3.2-qlc" -x "LD_LIBRARY_PATH=/export/cuda7/lib64:/usr/mpi/gcc/openmpi-1.3.2-qlc/lib64" ../build/nbody6++.sse.gpu.mpi < CometProject.input  1> nbody6.err.$LSB_JOBID 2>&1> nbody6.out.$LSB_JOBID
mpirun.lsf --prefix "/usr/mpi/gcc/openmpi-1.3.2-qlc" -x "LD_LIBRARY_PATH=/export/cuda7/lib64:/usr/mpi/gcc/openmpi-1.3.2-qlc/lib64" ../build/nbody6++.sse.mpi < CometProject.input  1> nbody6.err.$LSB_JOBID 2>&1> nbody6.out.$LSB_JOBID
